// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "./BatchTypes.sol";
import "./MintContract.sol";
import "./ControlContract.sol";

/**
 * @title VerificationContract
 * @notice Layer 3 of OriginPharm — read-only verification for all stakeholders.
 *
 * This contract has no state of its own and no write functions.
 * It reads from both MintContract and ControlContract and returns
 * the complete batch record in a single call.
 *
 * Used by:
 *   - Pharmacy: calls batchStatus(batchId) before receipt() to verify the on-chain
 *               record matches the physical delivery (medicine name, manufacturer,
 *               batch number, expiry date). If matched, proceeds to call receipt().
 *   - Consumer: scans QR code on medication box → reads batchId → calls batchStatus()
 *               to confirm the medicine completed the verified supply chain.
 *   - Regulator/Auditor: calls batchStatus() with batchId to audit the full
 *               custody trail and verified status of any batch.
 *
 * The QR code on the medication box encodes only the batchId.
 * All data lives on-chain. The QR code is generated by the application
 * layer when it detects the BatchReceived event from ControlContract.
 * It is printed by the pharmacist and attached to individual medication boxes.
 */


contract VerificationContract {

    // ─── State ────────────────────────────────────────────────────────────────

    /// @notice Reference to MintContract — source of batch data and verified status.
    MintContract public mintContract;

    /// @notice Reference to ControlContract — source of custody history and current custodian.
    ControlContract public controlContract;

    // ─── Constructor ──────────────────────────────────────────────────────────

    /**
     * @param mintContractAddress    Deployed address of MintContract.
     * @param controlContractAddress Deployed address of ControlContract.
     */
    constructor(address mintContractAddress, address controlContractAddress) {
        require(mintContractAddress != address(0), "VerificationContract: zero address");
        require(controlContractAddress != address(0), "VerificationContract: zero address");
        mintContract = MintContract(mintContractAddress);
        controlContract = ControlContract(controlContractAddress);
    }

    // helper to print status 
    function _statusLabel(BatchStatus status) internal pure returns (string memory) {
        if (status == BatchStatus.Produced)  return "Produced";
        if (status == BatchStatus.Released)  return "Released";
        if (status == BatchStatus.InTransit) return "InTransit";
        if (status == BatchStatus.Received)  return "Received";
        return "Unknown";
    }

    // ─── Verification Function ────────────────────────────────────────────────

    /**
     * @notice Returns the complete batch record for a given batchId.
     *         This is the single entry point for all stakeholders — pharmacy,
     *         consumer, regulator, and auditor.
     *
     *         Callable at any point in the batch lifecycle:
     *           After mintBatch():  status=Produced,  verified=false, empty trail
     *           After release():    status=Released,  verified=false, 1 custody record
     *           After shipment():   status=InTransit, verified=false, 2 custody records
     *           After receipt():    status=Received,  verified=true,  full trail
     *
     *         For consumers — only meaningful after the QR code exists on the box,
     *         which only happens after receipt() sets verified=true.
     *
     * @param batchId The unique batch identifier — scanned from QR code or searched directly.
     *
     * @return medicineName     Human-readable medicine name e.g. "Amoxicillin 500mg".
     * @return batchNumber      Manufacturer's internal batch reference e.g. "BATCH-001".
     * @return manufacturerName Owner-verified manufacturer name e.g. "Pfizer Australia Pty Ltd".
     * @return manufacturer     Wallet address of the minting manufacturer.
     * @return manufactureDate  Unix timestamp of when the batch was minted.
     * @return expiryDate       Unix timestamp of the batch expiry date.
     * @return status           Current BatchStatus enum value.
     * @return verified         True if receipt() has closed the cycle successfully.
     * @return currentOwner     Wallet address of the current batch custodian.
     * @return custodyTrail     Full ordered array of CustodyRecords from mint to present.
     */
     
     
    function batchStatus(uint256 batchId)
        external
        view
        returns (
            string memory medicineName,
            string memory batchNumber,
            string memory manufacturerName,
            address manufacturer,
            uint256 manufactureDate,
            uint256 expiryDate,
            string memory  status,
            bool verified,
            address currentOwner,
            CustodyRecord[] memory custodyTrail
        )
    {
        require(mintContract.batchExists(batchId), "VerificationContract: batch does not exist");

        BatchData memory batch = mintContract.getBatch(batchId);

        medicineName = batch.medicineName;
        batchNumber = batch.batchNumber;
        manufacturerName = batch.manufacturerName;
        manufacturer = batch.manufacturer;
        manufactureDate  = batch.manufactureDate;
        expiryDate = batch.expiryDate;
        status = _statusLabel(batch.status);
        verified = batch.verified;
        currentOwner = controlContract.currentCustodian(batchId);
        custodyTrail = controlContract.getCustodyHistory(batchId);
    }
}
